
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Create the SSL configuration file for Nginx
      copy:
        dest: /etc/nginx/conf.d/ssl.conf
        content: |
          server {
              listen 443 http2 ssl;
              listen [::]:443 http2 ssl;

              server_name server_IP_address;

              ssl_certificate {{certs_pass}};
              ssl_certificate_key {{certs_key_pass}};

              root /usr/share/nginx/html;

              location / {
                proxy_set_header        Host $host;
                proxy_set_header        X-Real-IP $remote_addr;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header        X-Forwarded-Proto $scheme;

                # Fix the â€œIt appears that your reverse proxy set up is broken" error.
                proxy_pass          http://{{proxy_pass_http}};
                proxy_read_timeout  90;
              }

              error_page 404 /404.html;
              location = /404.html {
              }

              error_page 500 502 503 504 /50x.html;
              location = /50x.html {
              }
          }

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted